--USE LibrairieExpress;

DROP TABLE IF EXISTS AFFILIATION;

DROP TABLE IF EXISTS THEMES;

DROP TABLE IF EXISTS POSSEDER;

DROP TABLE IF EXISTS EDITER;

DROP TABLE IF EXISTS ECRIRE;

DROP TABLE IF EXISTS DETAILCOMMANDE;

DROP TABLE IF EXISTS COMMANDE;

DROP TABLE IF EXISTS CLIENT;

DROP TABLE IF EXISTS MAGASIN;

DROP TABLE IF EXISTS LIVRE;

DROP TABLE IF EXISTS EDITEUR;

DROP TABLE IF EXISTS AUTEUR;

DROP TABLE IF EXISTS CLASSIFICATION;

DROP TABLE IF EXISTS VENDEUR;

DROP TABLE IF EXISTS ADMINISTRATEUR;